from pvz import *
from pvz.extra import *
import time
from speedrunmethods import *
import os

while(game_ui() != 2):
    Sleep(1)
start_time = time.time()
world_start_time = time.time()
WriteMemory("int",1,0x522598)
WriteMemory("int",1,0x522CB5)
os.system("python 3-1v3davefix.py")
print("3-1 " + str(time.time()-start_time))
print("3-1 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-2v4.py")
print("3-2 " + str(time.time()-start_time))
print("3-2 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-3v4.py")
print("3-3 " + str(time.time()-start_time))
print("3-3 Split " + str(time.time()-world_start_time))
press_enter()
WriteMemory("int",1,0x41CEA4)
start_time = time.time()
os.system("python 3-4v3.py")
print("3-4 " + str(time.time()-start_time))
print("3-4 Split " + str(time.time()-world_start_time))
press_enter()
WriteMemory("int",30000,0x41CEA4)
start_time = time.time()
os.system("python 3-5v2.py")
print("3-5 " + str(time.time()-start_time))
print("3-5 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-6v3.py")
print("3-6 " + str(time.time()-start_time))
print("3-6 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-7v2.py")
print("3-7 " + str(time.time()-start_time))
print("3-7 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-8v3.py")
print("3-8 " + str(time.time()-start_time))
print("3-8 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-9v2.py")
print("3-9 " + str(time.time()-start_time))
print("3-9 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 3-10.py")
print("3-10 " + str(time.time()-start_time))
print("3-10 Split! " + str(time.time()-world_start_time))