from pvz import *
from pvz.extra import *
import time
from speedrunmethods import *
import os

while(game_ui() != 2):
    Sleep(1)
start_time = time.time()
world_start_time = time.time()
WriteMemory("int", 1, 0x52B537) # corpse hp decay
WriteMemory("int",1,0x522598) # normal zombie x position
WriteMemory("int",1,0x522CB5) # vaulter x position
WriteMemory("int",1,0x523D1C) # garg x position
WriteMemory("int",1,0x45F1E1) # kenral always shoots butter
WriteMemory("int",1,0x522A11) # bungee starting altitude(did you know that was random???)
os.system("python 5-1v3.py")
print("5-1 " + str(time.time()-start_time))
print("5-1 Split " + str(time.time()-world_start_time))
press_enter()
while(ReadMemory("int",0x6A9EC0,0x844) != 4):
      Sleep(0.1)
press_enter()
press_enter()
press_enter()
press_enter()
press_enter()
press_enter()
left_click(440,280)
Sleep(150)
left_click(440,280)

press_enter()
press_enter()
left_click(600,280)
press_enter()
left_click(680,280)
press_enter()
press_enter()
left_click(545,360)
press_enter()
press_enter()
left_click(450,560)

Sleep(5)
start_time = time.time()
os.system("python 5-2v3.py")
print("5-2 " + str(time.time()-start_time))
print("5-2 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-3v2.py")
print("5-3 " + str(time.time()-start_time))
print("5-3 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-4.py")
print("5-4 " + str(time.time()-start_time))
print("5-4 Split " + str(time.time()-world_start_time))
press_enter()

start_time = time.time()
os.system("python 5-5v2ZGS.py")
print("5-5 " + str(time.time()-start_time))
print("5-5 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-6.py")
print("5-6 " + str(time.time()-start_time))
print("5-6 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-7v2.py")
print("5-7 " + str(time.time()-start_time))
print("5-7 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-8.py")
print("5-8 " + str(time.time()-start_time))
print("5-8 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-9v2.py")
print("5-9 " + str(time.time()-start_time))
print("5-9 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 5-10v2.py")
print("5-10 " + str(time.time()-start_time))
print("5-10 Split! " + str(time.time()-world_start_time))