from pvz import *
from pvz.extra import *
import time
import os
start_time = time.time()
world_start_time = time.time()
WriteMemory("int",1,0x522598)
WriteMemory("int",1,0x522CB5)
os.system("python 2-1v5.py")
print("2-1 " + str(time.time()-start_time))
print("2-1 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 2-2v3.py")
press_enter()
print("2-2 " + str(time.time()-start_time))
print("2-2 Split " + str(time.time()-world_start_time))
start_time = time.time()
WriteMemory("int",2500,0x41CEA4)
os.system("python 2-3v4.py")
print("2-3 " + str(time.time()-start_time))
print("2-3 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
WriteMemory("int",30000,0x41CEA4)
os.system("python 2-4v4.py")
print("2-4 " + str(time.time()-start_time))
print("2-4 Split " + str(time.time()-world_start_time))
safe_click()
press_enter()
for i in range(10):
    Sleep(2)
    left_down(720,580)
    Sleep(3)
left_up(720,580)
start_time = time.time()
os.system("2-5tas.py")
print("2-5 " + str(time.time()-start_time))
print("2-5 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
WriteMemory("int",100000,0x41CEA4)
os.system("python 2-6v3.py")
print("2-6 " + str(time.time()-start_time))
print("2-6 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 2-7v3.py")
print("2-7 " + str(time.time()-start_time))
print("2-7 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 2-8v3.py")
print("2-8 " + str(time.time()-start_time))
print("2-8 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 2-9v3.py")
print("2-9 " + str(time.time()-start_time))
print("2-9 Split " + str(time.time()-world_start_time))
press_enter()
start_time = time.time()
os.system("python 2-10.py")
print("2-10 " + str(time.time()-start_time))
print("2-10 Split! " + str(time.time()-world_start_time))

